In [1]:
%matplotlib notebook
#import SimpleITK as sitk
import cv2
import matplotlib.pyplot as plt
import numpy as np
#from utils.Transforms import Resample, Compose, RandomIntensityShiftScale, ElasticDeformation, RandomTranslate, RandomRotate, RandomScale, Input_to_Center, FitFixedAR, Origin_to_Output_Center

In [2]:
data = {"images":[".\\images_cropped\\"+str(id)+".jpg" for id in range(210)], "landmarks":[".\\landmarks_cropped\\"+str(id)+".txt" for id in range(210)]}

In [3]:
def plot_image(img, landmarks):
    plt.imshow(img, cmap="gray")
    plt.scatter(landmarks[:,0], landmarks[:,1], s=0.5)
    plt.show()

In [4]:
index = np.random.randint(0, 210)
mode = cv2.IMREAD_GRAYSCALE
#plot_image(cv2.imread(data['images'][index], mode), np.loadtxt(data['landmarks'][index]))

In [23]:
def remove_circles(img):
    circles = cv2.HoughCircles(img, cv2.HOUGH_GRADIENT,
                           dp=1.5, minDist=30, minRadius=15, maxRadius=60)
    print(circles)
    if circles is not None:
        black = np.zeros(img.shape)
        for x, y, r in circles[0]:
            cv2.circle(black, (x,y), int(r+15), 255, -1)  # -1 to draw filled circles
        bytemask = np.asarray(black, dtype=np.uint8)
        inpainted = cv2.inpaint(img, bytemask, inpaintRadius=5, flags=cv2.INPAINT_TELEA)
        return inpainted
    else :
        return img
    

In [24]:
index = 159#np.random.randint(0, 210)
print(index)
for index in range(210):
    img, landmarks = cv2.imread(data["images"][index], mode), np.loadtxt(data["landmarks"][index])
    img_circles_removed = remove_circles(img)
    cv2.imwrite(data["images"][index], img_circles_removed)
    #fig, (ax1, ax2) = plt.subplots(1, 2)
    #ax1.imshow(img, 'gray')
    #ax2.imshow(img_circles_removed, 'gray')
    #plt.show()
#plot_image(img, landmarks)

159
None
None
None
None
None
[[[ 35.25 389.25  57.9 ]]]
None
None
None
None
None
None
None
[[[126.75 347.25  35.25]]]
None
[[[  6.75 297.75  58.65]]]
None
None
None
None
None
None
[[[227.25 423.75  31.05]]]
[[[ 27.75 372.75  56.4 ]]]
None
None
None
None
None
None
None
None
None
[[[  3.75     341.25      54.449997]]]
None
None
None
[[[ 50.25 468.75  57.9 ]]]
None
[[[365.25     383.25      49.199997]
  [365.25     273.75      31.05    ]]]
None
None
[[[ 60.75 137.25  59.1 ]]]
[[[242.25 404.25  44.25]]]
[[[ 27.75 371.25  55.5 ]]]
[[[356.25     435.75      39.300003]]]
[[[387.75 396.75  32.7 ]]]
[[[233.25 395.25  36.  ]]]
[[[ 54.75     476.25      55.949997]]]
[[[338.25     428.25      29.400002]]]
None
None
None
None
None
None
[[[ 45.75 464.25  59.1 ]]]
None
None
None
None
[[[353.25 263.25  36.  ]]]
None
None
[[[ 60.75     440.25      55.050003]
  [174.75     344.25      50.85    ]
  [273.75     425.25      52.5     ]
  [327.75     425.25      45.9     ]
  [398.25     462.75      42.6     